services:
  - type: web
    name: nexchat
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GITHUB_STORAGE_REPO
        value: xMqrO/nexchat-data
      - key: GITHUB_TOKEN
        sync: false